apiVersion: v1
data:
    {{- toYaml .Values.configDefaults | nindent 2 }}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: tekton-default
    app.kubernetes.io/part-of: tekton-pipelines
  name: config-defaults