apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipelines-webhook
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: tekton-default
    app.kubernetes.io/part-of: tekton-pipelines
